import { AppHeader } from "@/components/AppHeader";
import { ArrowUpRight, BookOpen, ExternalLink, Map, ShieldAlert } from "lucide-react";
import { sectorPathways } from "@shared/advisor";
import { Link } from "wouter";

const resources = [
  ["Business Grants Portal (BGP)", "Submit and manage supported business grant applications.", "https://www.apply.gov.sg/grants/business"],
  ["EnterpriseSG", "Official source for PSG, EDG and MRA scheme terms.", "https://www.enterprisesg.gov.sg/financial-support"],
  ["SkillsFuture for Business", "Official source for SFEC, eligible training and WDG information.", "https://skillsfuture.gobusiness.gov.sg/support-and-programmes"],
  ["IMDA SMEs Go Digital", "Explore digital solutions, advisory resources and pathways for SMEs.", "https://www.imda.gov.sg/how-we-can-help/smes-go-digital"],
];

export default function Resources() {
  return <div className="min-h-screen bg-[#faf8f3] text-[#0b2947]"><AppHeader /><main className="site-shell py-14 sm:py-20"><div className="max-w-3xl"><p className="eyebrow">RESOURCE & ACTION HUB</p><h1 className="mt-3 font-display text-5xl leading-none tracking-[-.045em]">Official sources, arranged around the work to be done.</h1><p className="mt-5 text-lg leading-8 text-slate-600">Use these routes to verify live terms before a commitment. Scheme details, funding levels and application requirements can change; an approved Letter of Offer is the controlling document for your project.</p></div>
  <section className="mt-12 grid gap-4 md:grid-cols-2">{resources.map(([title, text, url], index) => <a key={title} href={url} target="_blank" rel="noreferrer" className="group rounded-2xl border border-[#0b2947]/9 bg-white p-6 shadow-[0_10px_32px_rgba(11,41,71,.04)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[0_18px_38px_rgba(11,41,71,.1)]"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e8eee9] text-[#3f746d]">{index % 2 ? <Map className="size-5" /> : <BookOpen className="size-5" />}</span><ExternalLink className="size-4 text-slate-400 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><h2 className="mt-6 text-xl font-extrabold tracking-tight">{title}</h2><p className="mt-2 leading-6 text-slate-600">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#3f746d]">Open official resource <ArrowUpRight className="size-3.5" /></span></a>)}</section>
  <section className="mt-16 rounded-[28px] border border-[#0b2947]/10 bg-[#eef4f1] p-7 sm:p-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow text-[#3f746d]">SECTOR PATHWAYS</p><h2 className="mt-2 font-display text-3xl tracking-[-.035em]">Start with the right industry context.</h2></div><Link href="/advisor" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#0b2947] px-5 py-3 text-sm font-bold text-white transition-transform hover:-translate-y-0.5 active:scale-[.97]">Run your diagnosis <ArrowUpRight className="size-4" /></Link></div><div className="mt-8 grid gap-3 md:grid-cols-2">{Object.entries(sectorPathways).filter(([key]) => key !== "other").map(([key, pathway]) => <a key={key} href={pathway.idpUrl} target="_blank" rel="noreferrer" className="rounded-2xl border border-[#0b2947]/8 bg-white/70 p-5 transition-colors hover:bg-white"><p className="font-extrabold">{pathway.label}</p><p className="mt-2 text-sm leading-6 text-slate-600">{pathway.focus}</p><p className="mt-4 text-xs font-bold tracking-[.1em] text-[#3f746d]">VIEW IMDA PATHWAY</p></a>)}</div></section>
  <section className="mt-10 flex gap-3 rounded-2xl border border-[#e0b34c]/30 bg-[#fff9ed] p-5"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-[#b27a14]" /><p className="text-sm leading-6 text-[#6f571d]"><strong>Before you commit:</strong> do not sign, pay or place a deposit until you have verified the live requirement for the specific scheme. In particular, no retrospective applications are supported for key project grants; EDG is reimbursement-based; and the current SFEC expires on 30 November 2026.</p></section>
  </main></div>;
}
